### PR TITLE
Feature/ita update

### LINKED ISSUE #632: Issue with Italian translation
Tested on 
Sony Xperia XZ1 - Android 9.0, Samsung Galaxy S4 - Android 10.0, Sony Xperia X - Android 9.0

## Steps to reproduce
After clicking "incominciamo", the sentence "knowledge is power" appears. It should be translated in Italian (to maintain consistency with the other pages). 

The expected translation is: sapere è potere

https://www.jotform.com/uploads/AppQuality/201096241235345/4632140126817427183/20200420_172437.jpg

### LINKED ISSUE #635: Typos in italian language translation
Error on   the transcription of the phrase "don't worry" in italian language.   You have written

Actual :
non preoccupati 

 Expected : "non pre occuparti". 

https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-26-35.jpg

Issue 2 in translation : 
 all subtitles are different from each other (e.g. some have the dot at the end and others don't)

Expected : all of them should be uniform.

https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-40-43.jpg   

https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-40-53.jpg   
https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-41-17.jpg

### PR DESCRIPTION
**Pull request by matteocrippa**
## Description

Improve italian localisation.

Minor cosmetic fixes after 0.9.5 test and add new key/value

Fixes #635  
Fixes #632

### CODE REVIEW

**Comment by alpita-masurkar** [comment]
@andreanuzzo can you review this?

**Comment by matteocrippa** [comment]
@andreanuzzo prolly both can fit, think I'm missing the context / user scenario for the database, I mean who's intended to provide that? Private healthcare entity, or public?
You know in italy if we refer to public are at the high level the ISS / Ministry of health, if we go at region level we deal with AST/ASL.

**Comment by andreanuzzo** [comment]
I know, I'm Italian :D 
I was thinking of common language. I think the most common word is `istituzioni`, at least from the articles I read. When I did the first translation I must have been distracted by the too many sources in English I've read so far. 

Since we aren't collaborating at the national or regional level, yet, I would not mention the ISS/SSN/ASL etc. But probably would remove the `autorità` anyway. If official collaboration start, we can mention the institutions by name.

Can you make those changes as well?

**Comment by matteocrippa** [comment]
@andreanuzzo migration done as suggested

**Comment by alpita-masurkar** [comment]
@matteocrippa Can you link #635 and #632 here?

**Comment by matteocrippa** [comment]
done

**Comment by summetj** [comment]
> done

To make it appear in the sidebar correctly, I believe you need the keyword before each issue number in the PR description above:

Fixes #635 
Fixes #632

**Comment by matteocrippa** [comment]
yep worked, thx @summetj

**Comment by tstirrat** [comment]
@alpita-masurkar @matteocrippa I updated this in Lokalise:

```
1 INSERTED 32 UPDATED 56 SKIPPED
```

**Pull request merged**
