### PR TITLE
Dutch Translation update, notifications translated Tijs van Wijk

### PR DESCRIPTION
**Pull request by alpita-masurkar**

### CODE REVIEW

**Comment by kenpugsley** [comment]
Thank you for this translation.  The UI has changed significantly and has now finalized for the v1.0 release, which has resulted in a great deal of changes to the text in the final app.  Because of this we found that it was best to remove the existing translations and start again.  Even though we are also closing this PR, we hope you understand and will help us again.

The text in the app is now complete, so **we're asking for your help to redo this translation on the text for the v1.0 release**.  Our translation lead @alpita-masurkar will be coordinating this effort.

Thank you from the COVID Safe Paths dev team.

**Comment by danoszz** [comment]
@alpita-masurkar I could redo the Dutch translations if needed. Shall I create a new issue?

**Comment by alpita-masurkar** [comment]
Hi @danoszz that'd be great! You can go ahead and do the translation.
One point to remember-
the name Safe Paths stays as is in the translation as it is the identity.

Let us know if you have any questions. We also have a slack group that is good for conversation and sharing related information. If you'd like to join, do share your email.

**Comment by danoszz** [comment]
@alpita-masurkar for sure, thank you! I will make a PR later today. I would love to join the slack group, my email is daan@devign.it

**Comment by alpita-masurkar** [comment]
done. you'll receive an invite soon.

**Pull request closed without merging**
