### PR TITLE
updated the text  and icon color for No data match.

### LINKED ISSUE #612: No Known Contact / No Data match Screen - Issues
## Version 0.9.5

- Type of phone: iPhone
- OS Version: 13.3
- Model: e.g. iPhone XR

## Steps to reproduce

1. Click on App icon 
2. tap on "get started "
3. set the location 
4. tap on " Finished Setup "
5. next screen will be the " No Known Contact " with green check sign.
6. displaying "Based on available data you haven't been near anyone reported positive for COVID-19. "

IMG-4520

## Expected Behavior

1.  Grey colour instead of green as per MVP Requirement  doc 
2. "No Data Match " and " Based on selected data sources, there is no data match at this time. "  instead of " No Known Contact " and  "Based on available data you haven't been near anyone reported positive for COVID-19. "

 in version 0.9.3 it was grey

IMG-4497

### PR DESCRIPTION
**Pull request by ArchanaNair**
Fixes #612 #607 

Updated the icon color and text as commented in No known contacts.

### CODE REVIEW

**Comment by Niniya173** [comment]
I think this issue is not merged into the latest version 1.0.1, because it seems to be the same green color icon for me in iPhone 5s, version 11.2.6

**Comment by tstirrat** [comment]
I think the grey color icon and "No Data Match" is outdated and refers to old UX. @driedgrape can confirm.

I'm going to close this for now, but @ArchanaNair you can consult with UX on slack to work out the latest here.

**Comment by ArchanaNair** [comment]
@tstirrat I dropped a message to @driedgrape on slack, will update here once I get confirmation.

**Comment by driedgrape** [comment]
@ArchanaNair, Tim is correct. Based on the most up-to-date specs, it should say "No known contact" with a green indicator.

"home_no_contact_header": "No known contact",
     "home_no_contact_subtext": "Based on available data you haven’t been near anyone reported positive for COVID-19.

**Pull request closed without merging**
