### PR TITLE
Feature/danish translation

### PR DESCRIPTION
**Pull request by martingd**
Danish translation from Jonas, Sofus and Martin Dawids.

### CODE REVIEW

**Comment by alpita-masurkar** [comment]
Hi @martingd thank you for contributing this translation! However, we've moved all of our translation efforts to a platform called Lokalise and are doing it through there.
The content of this app is rapidly evolving at this stage and it has been really helpful for translators to make updates when content changes through that platform and for us to automate this process.
Can you give me your email id so that I can send to you an invite for Lokalise and you can add this translation from there?
-Alpita

**Comment by martingd** [comment]
Hi @alpita-masurkar. Yes, sure. How do I send it to you?

**Comment by alpita-masurkar** [comment]
@martingd Thank you for responding so promptly! I just need your email id where I can send an invite to you.
If you want, you can send the email id here and delete it once I acknowledge it. I'm around for now if it helps.

**Comment by alpita-masurkar** [comment]
Sent an invite. @martingd is on Lokalise. Unless there's anything else, we can close this PR

**Pull request closed without merging**
