### PR TITLE
Change Import from webview to file picker

### PR DESCRIPTION
**Pull request by rparet**
Changes the Import screen and instructions from loading a web view to instructing the customer to get their takeout data from Google and then load it into PrivateKit using a file picker. 

Tested on iOS and Android via Google Drive / iCloud Drive.

### CODE REVIEW

**Comment by popofibo** [comment]
This effectively Resolves #77 & #114

**Comment by kenpugsley** [comment]
Once we have the dust fully settled from the rename to covid safe paths, we need to consider pulling this in, possibly for v1.0

**Comment by sergesemashko** [comment]
@rparet, I started digging into issues #73 and #77 the code from this PR would need to be merged first before addressing them. 

Also, Import feature is currently not really working properly in develop branch (need to fetch data for last 2 months, exceptions are thrown if files do not exist, racing conditions as async code is written in a sync way). 

Also, I'd like to offer some help to make this PR merged faster as I sort of got your idea and have an understanding how to address mentioned import issues.

**Comment by tremblerz** [comment]
@sergesemashko Can you branch off from the following one -
https://github.com/PrivateKit/private-kit/tree/import_picker
Once the issues are resolved we can test it and bring it inside the Safepaths

**Comment by rparet** [comment]
@sergesemashko that condition also exists on the current importer. It only looks for this month's date file, which is problematic in 2 ways: 1. at the start of the month (like now), a customer will only be able to import a short amount of date. 2. the import fails silently for people who don't have this month's data, which can be a lot of people if they turned location history off at any time in the last 12-24 months. 
I put this up as a PR because using the picker is a better solution for most customers, but if you want to make those enhancements I'd recommend surfacing to the customer when ENOENT is raised, as well as naively importing this month and last month's files.

**Comment by sergesemashko** [comment]
@rparet, yeah, picker solution seems to be friendlier. I can take a look at ENOENT and parsing latest 2 months of data and will open a PR soon.

**Comment by tstirrat** [comment]
closing in favor of rebased #410

**Pull request closed without merging**
