### PR TITLE
Changed notification text along with different languages

### PR DESCRIPTION
**Pull request by aartiverma1**
##Description:
Tap the "Location Active" button from settings. Notification text reads "Location tracking was Disabled"  followed by "PrivateKit requires location services"(text is confusing, as it implies the app does not have access to location services). Changed text to "Location Services stopped at user request" with different language support. ( issue #564 )

## How to test: 
Tap settings icon in top Right to get to the dashboard
Tap the "Location Active" button.

### CODE REVIEW

**Comment by summetj** [comment]
@alpita-masurkar - Impacts language translations for the changed notification string.

**Comment by alpita-masurkar** [comment]
@summetj @tstirrat @aartiverma1 @tremblerz There's also this #574 where this issue was discussed at length (unfortunately, it wasn't linked properly) and new text was suggested. Can we link these two and resolve this?

**Comment by summetj** [comment]
Closes  #564.

**Comment by tstirrat** [comment]
Superseded by #725

**Pull request closed without merging**
