### PR TITLE
Feature/apple watch

### PR DESCRIPTION
**Pull request by JohnMantegna**
## Description

Re: Issue #217 
Created an Apple Watch app to function as a companion app for COVID Safe Paths app.
As mentioned in the issue description, it is not yet integrated with the main iOS app.  I will be deferring that task to someone who knows React Native.

## How to test

Testing can proceed after integration.  Details in README
[README-CSP-Roam.pdf](https://github.com/tripleblindmarket/covid-safe-paths/files/4477320/README-CSP-Roam.pdf)

### CODE REVIEW

**Comment by kenpugsley** [comment]
Thanks so much for this!  Want to let you know the timing on this.  We're currently locking down for the v1 release, and we don't have the translator or testing bandwidth to include this in v1.  I'm adding the `Do Not Merge (yet)` and `for next next release` tags.  I'd like someone to come back and review this after the branch for v1.

**Comment by JohnMantegna** [comment]
Sounds good.  I have a separate Xcode project that demonstrates integration between the watch app and a generic iOS app that will be helpful for whomever is doing the react native integration.

**Comment by tstirrat** [comment]
Yeah, thanks for this.

Is this the kind of thing we'd need to communicate with it? https://github.com/mtford90/react-native-watch-connectivity

**Comment by JohnMantegna** [comment]
Yes

**Comment by tstirrat** [comment]
An update on this. We're working on adding "feature flags" to the build, so that this could be hidden behind a feature flag for iteration/testing in a beta channel.

**Comment by JohnMantegna** [comment]
When ready for integration, see this repo that contains the watch app code and a paired iOS app used for testing: https://github.com/JohnMantegna/PrivateKitTest-Watch-Roam

**Comment by tstirrat** [comment]
Thanks, tracked in Jira as https://pathcheck.atlassian.net/browse/SAF-128

**Pull request closed without merging**
