### PR TITLE
Set up face/touchID authentication using react-native-touch-id.

### PR DESCRIPTION
**Pull request by nic-rodriguez**
Works locally on iOS, yet to test on Android. 

The behavior works as follows:

Upon first opening the app, the user will be prompted to use Face/TouchID before being allowed to move to the next screen. I added the screen shown in the image to allow these users to bring up the prompt again if they cancelled by accident. I don't have any experience doing this type of work, so it's quite ugly and I could use some help to clean it up.

If a user does not have TouchID/FaceID enabled or available, then the authentication process is skipped.

IMG_3230

### CODE REVIEW

**Comment by penrods** [comment]
The user experience was a little odd on the emulator.  I tweaked it on the Android emulator.  Give it a shot on iOS and see how it feels to you.

**Comment by penrods** [comment]
Uninstall and start from scratch, it now only shows up after the startup sequence has completed.  You can also just turn off collection and shut down the app.

**Comment by tremblerz** [comment]
@nic-rodriguez are you still working on this?

**Comment by nic-rodriguez** [comment]
Yes, still working on it. Are there other changes that you would like me to make @tremblerz ?

**Comment by penrods** [comment]
If this works on your iPhone, go ahead and resolve the merge conflicts and we can pull it in.  I would like to use the same system in a couple other places later.

**Comment by nic-rodriguez** [comment]
No problems running on my iPhone XR locally. Also fixed merge conflicts. Thanks to whoever updated the UI, looks great!

**Comment by rparet** [comment]
@nic-rodriguez Looks like the build check is failing on this. Can you review?

**Comment by nic-rodriguez** [comment]
Just pushed the fix - I left a small typo in package.json when I was handing the merge conflicts. Builds cleanly now.

**Comment by tstirrat** [comment]
Hello, we made a drastic UI change with the V2 ui merge #354 . Can you please re-sync/merge this PR?

Thanks!

**Comment by kenpugsley** [comment]
I'm going to close this PR since we won't be merging it for v1.0.  If you think this is functionality important to the app, please open an issue so the need can be discussed there.

**Pull request closed without merging**
